version: "3.9"

services:
  web:
    container_name: bluetopiaworld
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1/" ]
      interval: 30s
      timeout: 5s
      retries: 3


